config/routes.rb
Rails.application.routes.draw do
  resources :workouts

  resources :exercises

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	has_many :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
	belongs_to :exercise
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:name, :note)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.order(params[:sort])
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:sets, :reps, :exercise_id, :timeCompleted, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<h1>Listing exercises</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.note %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @exercise.note %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExerciseSecond</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sets %><br>
    <%= f.number_field :sets %>
  </div>
  <div class="field">
    <%= f.label :reps %><br>
    <%= f.number_field :reps %>
  </div>
  <div class="field">
    <%= f.label "Time Completed" %><br>
    <%= f.datetime_select :timeCompleted %>
  </div>
  <div class="field">
    <%= f.label "Exercise" %><br>
    <%= collection_select :workout, :exercise_id, Exercise.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>Listing workouts</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to "Sets", :sort => "sets" %></th>
      <th><%= link_to "Reps", :sort => "reps" %></th>
      <th><%= link_to "Time Completed", :sort => "timeCompleted" %></th>
      <th><%= link_to "Exercise", :sort => "exercise_id" %></th>
      <th><%= link_to "Note", :sort => "note" %></th>
      <th "colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.sets %></td>
        <td><%= workout.reps %></td>
        <td><%= workout.timeCompleted %></td>
        <td><%= Exercise.find(workout.exercise_id).name %></td> 
        <td><%= workout.note %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sets:</strong>
  <%= @workout.sets %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @workout.reps %>
</p>

<p>
  <strong>Time Completed:</strong>
  <%= @workout.timeCompleted %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= Exercise.find(@workout.exercise_id).name %>
</p>
<p>
  <strong>Note:</strong>
  <%= @workout.note %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>